apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-edit
subjects:
  - kind: ServiceAccount
    name: github
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token
