discordToken: ""

replicaCount: 1

image:
  repository: unlimitedsola/laoshi-plus-plus
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
