apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laoshi-plus-plus.fullname" . }}
type: Opaque
data:
  DISCORD_TOKEN: |-
        {{ required ".Values.discordToken must be specified!" .Values.discordToken | b64enc }}
