name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ publish ]
    types: [ completed ]
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        env:
          HELM_KUBEAPISERVER: ${{ secrets.KUBEAPISERVER }}
          HELM_KUBETOKEN: ${{ secrets.KUBETOKEN }}
          HELM_NAMESPACE: laoshi-plus-plus
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          helm upgrade --install laoshi-plus-plus k8s --set image.tag=${{ github.sha }} --set discordToken=$DISCORD_TOKEN
