name: Publish
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ check ]
    types: [ completed ]
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Docker Hub
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jib
            --image=${{ github.repository }}
            -Djib.to.tags=latest,${{ github.sha }}
